# Generated by Django 4.0 on 2024-09-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_followers_customuser_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='maxsmithbusiness198@gmail.com', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
