# Generated by Django 5.1.1 on 2024-10-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_email'),
        ('elo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='elos',
            field=models.ManyToManyField(related_name='elo_s', to='elo.elo'),
        ),
    ]
