# Generated by Django 5.1.1 on 2024-11-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_elos'),
        ('clubs', '0020_dummyuser_biological_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clubs',
            field=models.ManyToManyField(related_name='club_s', to='clubs.clubmodel'),
        ),
    ]
