# Generated by Django 4.2 on 2025-01-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verify',
            field=models.BooleanField(default=False),
        ),
    ]
