# Generated by Django 4.2 on 2025-02-09 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuser_first_name_alter_customuser_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9._-]*$', 'Username can only contain letters and numbers.')]),
        ),
    ]
