# Generated by Django 5.1.1 on 2024-11-19 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0001_initial'),
        ('games', '0005_gametype_game_game_type2'),
    ]

    operations = [
        migrations.AddField(
            model_name='elo',
            name='game_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.gametype'),
        ),
    ]
