# Generated by Django 5.1.1 on 2024-10-07 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0017_delete_event'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('badminton_singles', 'Badminton Singles'), ('badminton_doubles', 'Badminton Doubles'), ('tennis_singles', 'Tennis Singles'), ('tennis_doubles', 'Tennis Doubles'), ('paddle_singles', 'Paddle Singles'), ('paddle_doubles', 'Paddle Doubles')], max_length=50)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('number_of_courts', models.PositiveIntegerField()),
                ('sbmm', models.BooleanField(default=False)),
                ('guests_allowed', models.BooleanField(default=False)),
                ('over_18_under_18_mixed', models.CharField(choices=[('over_18', 'Over 18'), ('under_18', 'Under 18'), ('all ages', 'All ages')], max_length=10)),
                ('event_active', models.BooleanField(default=False)),
                ('event_complete', models.BooleanField(default=False)),
                ('active_members', models.ManyToManyField(blank=True, related_name='active_events', to='clubs.member')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.clubmodel')),
                ('games', models.ManyToManyField(blank=True, to='games.game')),
                ('played_one_match', models.ManyToManyField(blank=True, related_name='played_matches', to='clubs.member')),
            ],
        ),
    ]
