# Generated by Django 5.1.1 on 2024-10-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_delete_event'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ready_members',
            field=models.ManyToManyField(blank=True, related_name='ready_events', to='clubs.member'),
        ),
    ]
