# Generated by Django 5.1.1 on 2024-10-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_ready_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ready_members',
        ),
    ]
