# Generated by Django 5.1.1 on 2024-10-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_ready_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='player_match_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
