# Generated by Django 5.1.1 on 2024-10-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_delete_event'),
        ('events', '0004_event_player_match_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='in_game_members',
            field=models.ManyToManyField(blank=True, related_name='in_game_members', to='clubs.member'),
        ),
    ]
