# Generated by Django 5.1.1 on 2024-10-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_in_game_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='even_teams',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='mode',
            field=models.CharField(choices=[('sbmm', 'SBMM'), ('social', 'Social'), ('peg_board', 'Peg Board')], default='SBMM', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='sbmm',
            field=models.BooleanField(default=True),
        ),
    ]
