# Generated by Django 5.1.1 on 2024-10-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_even_teams_event_mode_alter_event_sbmm'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='best_winstreak',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='event',
            name='wins',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='event',
            name='winstreaks',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
