# Generated by Django 5.1.1 on 2024-10-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_best_winstreak_event_wins_event_winstreaks'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='final_elo',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='event',
            name='intial_elo',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
