# Generated by Django 5.1.1 on 2024-10-30 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_final_elo_event_intial_elo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='intial_elo',
            new_name='initial_elo',
        ),
    ]
