# Generated by Django 5.1.1 on 2024-11-18 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_rename_intial_elo_event_initial_elo'),
        ('games', '0005_gametype_game_game_type2'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='game_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.gametype'),
        ),
    ]
