# Generated by Django 5.1.1 on 2024-11-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_game_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sport',
        ),
    ]
