# Generated by Django 5.1.1 on 2024-12-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_event_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='played_with',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
