# Generated by Django 4.0 on 2024-09-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Club',
            new_name='ClubModel',
        ),
    ]
