# Generated by Django 4.0 on 2024-09-22 20:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_email'),
        ('clubs', '0002_rename_club_clubmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmodel',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clubmodel',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubmodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='club_logos'),
        ),
        migrations.AddField(
            model_name='clubmodel',
            name='president',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clubs_presided', to='accounts.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubmodel',
            name='signup_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubmodel',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClubAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs_administered', to='accounts.customuser')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='clubs.clubmodel')),
            ],
            options={
                'unique_together': {('club', 'admin')},
            },
        ),
    ]
