# Generated by Django 4.0 on 2024-09-27 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_memberrequest_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberrequest',
            old_name='date_joined',
            new_name='date_requested',
        ),
    ]
