# Generated by Django 4.0 on 2024-09-28 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_email'),
        ('clubs', '0006_rename_date_joined_memberrequest_date_requested'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='memberrequest',
            unique_together={('club', 'user')},
        ),
    ]
