# Generated by Django 5.1.1 on 2024-10-03 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_alter_memberrequest_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('badminton_singles', 'Badminton Singles'), ('badminton_doubles', 'Badminton Doubles'), ('tennis_singles', 'Tennis Singles'), ('tennis_doubles', 'Tennis Doubles'), ('paddle_singles', 'Paddle Singles'), ('paddle_doubles', 'Paddle Doubles')], max_length=20)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('players', models.ManyToManyField(to='clubs.member')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('badminton', 'Badminton'), ('tennis', 'Tennis'), ('paddle', 'Paddle')], max_length=10)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('number_of_courts', models.PositiveIntegerField()),
                ('sbmm', models.BooleanField(default=False)),
                ('guests_allowed', models.BooleanField(default=False)),
                ('over_18_under_18_mixed', models.CharField(choices=[('over_18', 'Over 18'), ('under_18', 'Under 18'), ('all ages', 'All ages')], max_length=10)),
                ('active_members', models.ManyToManyField(related_name='active_events', to='clubs.member')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.clubmodel')),
                ('paused_members', models.ManyToManyField(related_name='paused_inactive_events', to='clubs.member')),
                ('played_one_match', models.ManyToManyField(related_name='played_matches', to='clubs.member')),
                ('games', models.ManyToManyField(to='clubs.game')),
            ],
        ),
    ]
