# Generated by Django 5.1.1 on 2024-10-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_game_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='games',
            field=models.ManyToManyField(blank=True, null=True, to='clubs.game'),
        ),
    ]
