# Generated by Django 5.1.1 on 2024-10-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_alter_event_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='active_members',
            field=models.ManyToManyField(blank=True, related_name='active_events', to='clubs.member'),
        ),
        migrations.AlterField(
            model_name='event',
            name='paused_members',
            field=models.ManyToManyField(blank=True, related_name='paused_inactive_events', to='clubs.member'),
        ),
        migrations.AlterField(
            model_name='event',
            name='played_one_match',
            field=models.ManyToManyField(blank=True, related_name='played_matches', to='clubs.member'),
        ),
    ]
