# Generated by Django 5.1.1 on 2024-10-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_alter_event_active_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sport',
            field=models.CharField(choices=[('badminton_singles', 'Badminton Singles'), ('badminton_doubles', 'Badminton Doubles'), ('tennis_singles', 'Tennis Singles'), ('tennis_doubles', 'Tennis Doubles'), ('paddle_singles', 'Paddle Singles'), ('paddle_doubles', 'Paddle Doubles')], max_length=50),
        ),
    ]
