# Generated by Django 5.1.1 on 2024-10-05 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_alter_event_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='paused_members',
        ),
    ]
