# Generated by Django 5.1.1 on 2024-10-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_remove_event_paused_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_complete',
            field=models.BooleanField(default=True),
        ),
    ]
