# Generated by Django 5.1.1 on 2024-10-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_event_event_active_event_event_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_complete',
            field=models.BooleanField(default=False),
        ),
    ]
