# Generated by Django 5.1.1 on 2024-10-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_alter_event_event_active_alter_event_event_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='games',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
