# Generated by Django 5.1.1 on 2024-10-07 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_remove_event_games_delete_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
