# Generated by Django 5.1.1 on 2024-10-19 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_delete_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmodel',
            name='bots',
            field=models.ManyToManyField(related_name='bots', to=settings.AUTH_USER_MODEL),
        ),
    ]
