# Generated by Django 5.1.1 on 2024-10-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0019_dummyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummyuser',
            name='biological_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
    ]
