# Generated by Django 5.1.1 on 2024-11-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0020_dummyuser_biological_gender'),
        ('events', '0009_rename_intial_elo_event_initial_elo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmodel',
            name='events',
            field=models.ManyToManyField(related_name='events', to='events.event'),
        ),
    ]
