# Generated by Django 5.1.1 on 2024-11-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0021_clubmodel_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmodel',
            name='members',
            field=models.ManyToManyField(related_name='members', to='clubs.member'),
        ),
    ]
