# Generated by Django 5.1.1 on 2024-11-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0023_member_is_admin_member_is_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmodel',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubmodel',
            name='full_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
