# Generated by Django 5.1.1 on 2024-11-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0024_clubmodel_coordinates_clubmodel_full_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubmodel',
            old_name='full_address',
            new_name='address',
        ),
    ]
