# Generated by Django 5.1.1 on 2024-11-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0025_rename_full_address_clubmodel_address'),
        ('events', '0009_rename_intial_elo_event_initial_elo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clubadmin',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='clubadmin',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='clubadmin',
            name='club',
        ),
        migrations.AlterField(
            model_name='clubmodel',
            name='events',
            field=models.ManyToManyField(related_name='club_events', to='events.event'),
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('clubs', models.ManyToManyField(related_name='clubs', to='clubs.clubmodel')),
            ],
        ),
    ]
