# Generated by Django 5.1.1 on 2024-11-18 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0026_alter_clubadmin_unique_together_and_more'),
        ('games', '0005_gametype_game_game_type2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='game_types',
            field=models.ManyToManyField(related_name='game_types', to='games.gametype'),
        ),
        migrations.AddField(
            model_name='clubmodel',
            name='sport2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.sport'),
        ),
        migrations.DeleteModel(
            name='ClubAdmin',
        ),
    ]
