# Generated by Django 5.1.1 on 2024-11-19 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0027_sport_game_types_clubmodel_sport2_delete_clubadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubmodel',
            old_name='sport2',
            new_name='sport_type',
        ),
    ]
