# Generated by Django 5.1.1 on 2024-11-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0028_rename_sport2_clubmodel_sport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmodel',
            name='club_username',
            field=models.CharField(max_length=12),
        ),
    ]
