# Generated by Django 5.1.1 on 2024-11-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0029_alter_clubmodel_club_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmodel',
            name='info',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
    ]
