# Generated by Django 5.1.1 on 2024-11-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0030_alter_clubmodel_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_event', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='clubmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
