# Generated by Django 5.1.1 on 2024-11-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0031_clubstatus_clubmodel_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubstatus',
            old_name='last_event',
            new_name='event_dates',
        ),
    ]
