# Generated by Django 5.1.1 on 2024-12-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0033_remove_clubmodel_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubmodel',
            name='signup_link',
        ),
        migrations.RemoveField(
            model_name='clubmodel',
            name='website',
        ),
        migrations.AddField(
            model_name='clubmodel',
            name='socials',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
