# Generated by Django 5.1.1 on 2024-10-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0016_remove_event_games_delete_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('badminton_singles', 'Badminton Singles'), ('badminton_doubles', 'Badminton Doubles'), ('tennis_singles', 'Tennis Singles'), ('tennis_doubles', 'Tennis Doubles'), ('paddle_singles', 'Paddle Singles'), ('paddle_doubles', 'Paddle Doubles')], max_length=20)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('all_users', models.ManyToManyField(related_name='all_user_games', to='clubs.member')),
                ('team1', models.ManyToManyField(related_name='team1_games', to='clubs.member')),
                ('team2', models.ManyToManyField(related_name='team2_games', to='clubs.member')),
            ],
        ),
    ]
