# Generated by Django 5.1.1 on 2024-10-09 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('badminton_singles', 'Badminton Singles'), ('badminton_doubles', 'Badminton Doubles'), ('tennis_singles', 'Tennis Singles'), ('tennis_doubles', 'Tennis Doubles'), ('paddle_singles', 'Paddle Singles'), ('paddle_doubles', 'Paddle Doubles')], max_length=20)),
                ('elo', models.IntegerField(default=1000)),
                ('last_game', models.DateField(default=django.utils.timezone.now)),
                ('winstreak', models.IntegerField(default=0)),
                ('best_winstreak', models.IntegerField(default=0)),
                ('game_loses', models.ManyToManyField(related_name='loses', to='games.game')),
                ('game_wins', models.ManyToManyField(related_name='wins', to='games.game')),
            ],
        ),
    ]
