# Generated by Django 5.1.1 on 2024-10-10 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_elo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Elo',
        ),
    ]
