# Generated by Django 5.1.1 on 2024-11-18 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0026_alter_clubadmin_unique_together_and_more'),
        ('events', '0009_rename_intial_elo_event_initial_elo'),
        ('games', '0004_game_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('events', models.ManyToManyField(related_name='game_type_events', to='events.event')),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.sport')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.gametype'),
        ),
    ]
