# Generated by Django 5.1.1 on 2024-11-19 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_gametype_game_game_type2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_type2',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.gametype'),
        ),
    ]
