# Generated by Django 5.1.1 on 2024-12-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_remove_game_game_type2_alter_game_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametype',
            name='team_size',
            field=models.IntegerField(default=2, editable=False),
        ),
    ]
